databases:
  - name: swa
    databaseName: afectacion_db
    user: afectacion_db_user

services:
  - type: web
    name: swa
    env: python
    buildCommand: "./render/build.sh"
    startCommand: "gunicorn swa.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afectacion_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4