# Generated by Django 3.2.19 on 2023-06-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('idUniversidad', models.AutoField(primary_key=True, serialize=False)),
                ('anio_periodo', models.IntegerField()),
                ('nombreU', models.CharField(max_length=50)),
                ('numDesertados', models.IntegerField()),
                ('numGraduados', models.IntegerField()),
                ('numInscritos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('idEstadistica', models.AutoField(primary_key=True, serialize=False)),
                ('anio_dato', models.IntegerField()),
                ('tipoGrafico', models.CharField(max_length=25)),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.administrador')),
                ('idUniversidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.universidad')),
            ],
        ),
    ]
