# Generated by Django 3.2.19 on 2023-06-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contrasenia',
            field=models.CharField(max_length=120),
        ),
    ]
