# Generated by Django 3.2.19 on 2023-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_administrador_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='idUniversidad',
            field=models.AutoField(db_column='idUniversidad', primary_key=True, serialize=False),
        ),
    ]
