# Generated by Django 3.2.19 on 2023-06-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_universidad_iduniversidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='idUniversidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
